timer: 300
votetimer: 15
waittimer: 60
wintimer: 10

loading:
  load-after-plugins: true

allow-fly-out-bounds: false
enable-subject-voting: true
restore-plots: true
scoreboard-update-delay: 20
max-vote-change: -1
max-particles: -1
names-after-voting: false
enable-item-drop: false

stats:
  enable: true
  save-delay: 900
  database:
    enable: false
    address: 'jdbc:mysql://localhost:3306/<databasename>'
    user: '<user>'
    password: '<password>'
    min-connections: 5
    max-connections: 10

subjects:
- dog
- house
- toilet
- superman
- superhero
- car
- book
- candy
- flower
- headset

scoreboards:
  main:
    enable: true
    worlds:
      enable:
      -

blocked-entities:
- 'ender_crystal'
- 'ender_dragon'
- 'wither'

blocks:
  blocked:
  - 'command'
  - 'command_minecart'

bossbar:
  color: purple
  style: solid

mobs:
  enable-noai: true
  allow: true

title:
  fade_in: 0
  stay: 20
  fade_out: 20
  syncronize: false

voting:
  default-vote-points: 5
  second-slot:
    id: 'coal_block'
    points: 2
  third-slot:
    id: 'iron_block'
    points: 3
  fourth-slot:
    id: 'lapis_block'
    points: 4
  fifth-slot:
    id: 'redstone_block'
    points: 5
  sixth-slot:
    id: 'gold_block'
    points: 6
  seventh-slot:
    id: 'diamond_block'
    points: 7
  eighth-slot:
    id: 'emerald_block'
    points: 8

command-whitelist:
- give
- gamemode

timings:
  lobby-timer:
    at:
      10:
      - 'tellraw @a ["",{"text":"Hurry up, ","color":"aqua"},{"selector":"@p","color":"gold","italic":true},{"text":", %arena% is starting soon!","color":"aqua"}]'
    every:
  build-timer:
    at:
    every:
  vote-timer:
    at:
    every:
  win-timer:
    at:
    every:

join:
  time-change:
    change: true
    time: 6000

win-commands:
- 'execute %winner% ~1 ~ ~-4 summon FireworksRocketEntity ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:0,Colors:[14263784,581228,995542,3255052,13888116,4175055],FadeColors:[8848460]}]}}}}'
- 'execute %winner% ~-2 ~ ~3 summon FireworksRocketEntity ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:2,Colors:[14495340,12909992,8969028,7924605],FadeColors:[10438567,12267580,2724499,9942861]}]}}}}'
- 'execute %winner% ~-4 ~ ~1 summon FireworksRocketEntity ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:0,Colors:[2540754],FadeColors:[14655338,2417053,631931,4555299,15572482,3482736,693669]}]}}}}'

hotbar:
  default:
    slot-1: air
    slot-2: air
    slot-3: air
    slot-4: air
    slot-5: air
    slot-6: air
    slot-7: air
    slot-8: air
    slot-9: air

money:
  first: 20
  second: 10
  third: 5
  others: 0
commands:
  first:
  -
  second:
  -
  third:
  -
  others:
  -

leave-item:
  slot: 0
  id: 'watch'

subject-gui:
  item:
    id: 'paper'
  subject-amount: -1
  slot: 8

bungeecord:
  enable: false
  
team-selection:
  show-names-as-lore: false
  item:
    id: 'paper'
  team:
    1:
      id: 'paper'
  
gui:
  slot: 8
  particles:
    id: 'red_rose'
    enabled: true
  floor: 
    id: 'hard_clay'
    enabled: true
  time:
    id: 'watch'
    enabled: true
  rain:
    id: 'water_bucket'
    enabled: true
  fly-speed:
    id: 'feather'
    enabled: true
  heads:
    id: 'skull_item:3'
    enabled: true

debug: false
clean-files: false